            - name: Readme Replacer - Readme-Workflows
  # You may pin to the exact commit or the version.
  # uses: Readme-Workflows/readme-replacer@476f6f7ca5f3a0e7d3a55712d70227845ea3c3b6
  uses: Readme-Workflows/readme-replacer@v1.0.1
  with:
    # Your GitHub username
    GH_USERNAME: # optional, default is ${{ github.repository_owner }}
    # Path to template file
    TEMPLATE_FILE: # optional, default is ./TEMPLATE.md
    # Path to commit file
    COMMIT_FILE: # optional, default is ./README.md
    # Path to custom replacer file (JSON). You can select if you want to use eval or not!
    CUSTOM_REPLACER_FILE: # optional, default is ./.github/customReplacer.json
    # Format of the date/time (if date replacer used)
    DATE_FORMAT: # optional, default is dddd, mmmm dS, yyyy, h:MM:ss TT
    # Desired timezone of the date (can be locale based of GMT offset)
    TIMEZONE: # optional, default is 0
    # Message used for committing changes
    COMMIT_MESSAGE: # optional, default is ⚡ Update README by replacing keywords
    # Email used for committing changes
    COMMIT_EMAIL: # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
    # Name used for committing changes
    COMMIT_NAME: # optional, default is replacer-bot
          
