- name: Readme Replacer - Readme-Workflows
  uses: Readme-Workflows/readme-replacer@v1.0.1
  with:
    # GitHub username
    GH_USERNAME: ${{ Rorschach3 }}  

    # template file
    TEMPLATE_FILE: ./TEMPLATE.md  

    # commit file
    COMMIT_FILE: ./README.md  # Provide the correct path to your README file

    # Path to custom replacer file (JSON). You can select if you want to use eval or not!
    CUSTOM_REPLACER_FILE: ./.github/customReplacer.json

    # Format of the date/time
    DATE_FORMAT: 'dddd, mmmm dS, yyyy, h:MM:ss TT' 

    # Desired timezone of the date 
    TIMEZONE: '0'

    # Message used for committing changes
    COMMIT_MESSAGE: "⚡ Update README by replacing keywords"

    # Email used for committing changes
    COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

    # Name used for committing changes
    COMMIT_NAME: replacer-bot 
